# Generated by Django 5.2.2 on 2025-06-24 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0019_pontoatendimentoinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='bipagem',
            name='estado',
            field=models.CharField(choices=[('1', 'Excelente'), ('2', 'Bom'), ('3', 'Ruim'), ('4', 'Péssimo')], max_length=100, null=True),
        ),
    ]
