# Generated by Django 5.2.2 on 2025-06-24 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0020_bipagem_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bipagem',
            name='estado',
            field=models.CharField(choices=[('Excelente', 'Excelente'), ('Bom', 'Bom'), ('Ruim', 'Ruim'), ('Péssimo', 'Péssimo')], max_length=100, null=True),
        ),
    ]
