# Generated by Django 5.2.2 on 2025-06-24 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('inventario', '0021_alter_bipagem_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='bipagem',
            name='group_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.group'),
        ),
        migrations.AddConstraint(
            model_name='bipagem',
            constraint=models.UniqueConstraint(fields=('nrserie', 'group_user'), name='unique_serial_por_pa'),
        ),
    ]
