# Generated by Django 5.2.2 on 2025-06-25 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0022_bipagem_group_user_bipagem_unique_serial_por_pa'),
    ]

    operations = [
        migrations.AddField(
            model_name='pontoatendimentoinfo',
            name='limite',
            field=models.IntegerField(choices=[(10, '10 bipagens'), (20, '20 bipagens'), (30, '30 bipagens'), (50, '50 bipagens')], default=50, verbose_name='Limite de bipagens'),
            preserve_default=False,
        ),
    ]
