# Generated by Django 5.2.2 on 2025-06-25 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0023_pontoatendimentoinfo_limite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pontoatendimentoinfo',
            name='limite',
            field=models.IntegerField(choices=[(10, '10 bipagens'), (20, '20 bipagens'), (30, '30 bipagens'), (50, '50 bipagens')], default=50, verbose_name='Limite de bipagens'),
        ),
    ]
