# Generated by Django 5.2.2 on 2025-06-25 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0024_alter_pontoatendimentoinfo_limite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pontoatendimentoinfo',
            name='limite',
            field=models.IntegerField(choices=[(50, '50 bipagens'), (100, '100 bipagens'), (150, '150 bipagens'), (300, '300 bipagens')], default=50, verbose_name='Limite de bipagens'),
        ),
    ]
