# Generated by Django 5.2.2 on 2025-06-25 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0025_alter_pontoatendimentoinfo_limite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pontoatendimentoinfo',
            name='limite',
            field=models.IntegerField(default=50, verbose_name='Limite de bipagens'),
        ),
    ]
