# Generated by Django 5.2.2 on 2025-06-25 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0026_alter_pontoatendimentoinfo_limite'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='bipagem',
            name='unique_serial_por_pa',
        ),
    ]
