# Generated by Django 5.2.2 on 2025-06-30 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('inventario', '0027_remove_bipagem_unique_serial_por_pa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bipagem',
            name='estado',
            field=models.CharField(choices=[('GOOD', 'GOOD'), ('BAD', 'BAD'), ('OBSOLETO', 'OBSOLETO'), ('TRIAGEM', 'TRIAGEM')], max_length=100, null=True),
        ),
        migrations.AddConstraint(
            model_name='bipagem',
            constraint=models.UniqueConstraint(fields=('nrserie', 'group_user'), name='unique_serial_por_pa'),
        ),
    ]
