# Generated by Django 5.2.2 on 2025-06-30 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0028_inventariodadosimportados_alter_bipagem_estado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventarioDadosImportados',
            fields=[
                ('modalidade_comercial', models.CharField(max_length=100)),
                ('material', models.IntegerField()),
                ('serial', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('modelo', models.CharField(max_length=200)),
                ('status_sistema', models.CharField(max_length=50)),
                ('status_usuario', models.CharField(max_length=50)),
                ('opl', models.IntegerField()),
                ('serial_fabricante', models.CharField(max_length=100)),
                ('equipamento', models.IntegerField()),
                ('centro', models.IntegerField()),
                ('deposito', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('modificado_por', models.CharField(blank=True, max_length=100, null=True)),
                ('modificado_em', models.DateField(blank=True, null=True)),
                ('ct', models.CharField(blank=True, max_length=50, null=True)),
                ('data_aquisicao', models.DateField(blank=True, null=True)),
                ('nome_ct', models.CharField(blank=True, max_length=100, null=True)),
                ('nome_fornecedor', models.CharField(blank=True, max_length=200, null=True)),
                ('acao', models.CharField(blank=True, max_length=50, null=True)),
                ('mensagem_ferramenta_inv', models.CharField(blank=True, max_length=100, null=True)),
                ('vl_aquisicao', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('vl_residual', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'verbose_name': 'Inventário Importado',
                'verbose_name_plural': 'Inventários Importados',
                'db_table': 'inventario_dados_importados',
            },
        ),
    ]
