# Generated by Django 5.2.2 on 2025-07-03 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0029_inventariodadosimportados'),
    ]

    operations = [
        migrations.AddField(
            model_name='bipagem',
            name='mensagem_ferramenta_inv',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bipagem',
            name='observacao',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bipagem',
            name='estado',
            field=models.CharField(blank=True, choices=[('GOOD', 'GOOD'), ('BAD', 'BAD'), ('OBSOLETO', 'OBSOLETO'), ('TRIAGEM', 'TRIAGEM')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='lotebipagem',
            name='status',
            field=models.CharField(choices=[('aberto', 'Aberto'), ('fechado', 'Fechado'), ('aguardando validação', 'Aguardando Validação'), ('invalidado', 'Invalidado')], default='Aberto', max_length=20),
        ),
    ]
