# Generated by Django 5.2.2 on 2025-07-03 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0030_bipagem_mensagem_ferramenta_inv_bipagem_observacao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bipagem',
            name='mensagem_ferramenta_inv',
        ),
    ]
