# Generated by Django 5.2.2 on 2025-07-03 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0031_remove_bipagem_mensagem_ferramenta_inv'),
    ]

    operations = [
        migrations.AddField(
            model_name='bipagem',
            name='mensagem_ferramenta_inv',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
