# Generated by Django 5.2.2 on 2025-07-04 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0032_bipagem_mensagem_ferramenta_inv'),
    ]

    operations = [
        migrations.AddField(
            model_name='bipagem',
            name='comentarios',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
