# Generated by Django 5.2.2 on 2025-07-10 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0033_bipagem_comentarios'),
    ]

    operations = [
        migrations.AddField(
            model_name='pontoatendimentoinfo',
            name='login_liberado',
            field=models.BooleanField(default=False, verbose_name='Login liberado?'),
        ),
    ]
