# Generated by Django 5.2.2 on 2025-07-10 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0035_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pontoatendimentoinfo',
            name='login_liberado',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
