# Generated by Django 5.2.2 on 2025-07-10 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0036_remove_pontoatendimentoinfo_login_liberado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pontoatendimentoinfo',
            name='liberado',
            field=models.BooleanField(default=True, verbose_name='Acesso liberado'),
        ),
    ]
