# Generated by Django 5.2.2 on 2025-07-10 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0037_pontoatendimentoinfo_liberado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pontoatendimentoinfo',
            name='liberado',
            field=models.BooleanField(default=False, verbose_name='Acesso liberado'),
        ),
    ]
