# Generated by Django 5.2.2 on 2025-07-14 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0038_alter_pontoatendimentoinfo_liberado'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='bipagem',
            name='unique_serial_por_pa',
        ),
        migrations.RemoveField(
            model_name='inventariodadosimportados',
            name='acao',
        ),
        migrations.RemoveField(
            model_name='inventariodadosimportados',
            name='centro',
        ),
        migrations.RemoveField(
            model_name='inventariodadosimportados',
            name='ct',
        ),
        migrations.RemoveField(
            model_name='inventariodadosimportados',
            name='data_aquisicao',
        ),
        migrations.RemoveField(
            model_name='inventariodadosimportados',
            name='deposito',
        ),
        migrations.RemoveField(
            model_name='inventariodadosimportados',
            name='equipamento',
        ),
        migrations.RemoveField(
            model_name='inventariodadosimportados',
            name='material',
        ),
        migrations.RemoveField(
            model_name='inventariodadosimportados',
            name='modalidade_comercial',
        ),
        migrations.RemoveField(
            model_name='inventariodadosimportados',
            name='modificado_em',
        ),
        migrations.RemoveField(
            model_name='inventariodadosimportados',
            name='modificado_por',
        ),
        migrations.RemoveField(
            model_name='inventariodadosimportados',
            name='nome_fornecedor',
        ),
        migrations.RemoveField(
            model_name='inventariodadosimportados',
            name='opl',
        ),
        migrations.RemoveField(
            model_name='inventariodadosimportados',
            name='status_sistema',
        ),
        migrations.RemoveField(
            model_name='inventariodadosimportados',
            name='status_usuario',
        ),
        migrations.RemoveField(
            model_name='inventariodadosimportados',
            name='vl_aquisicao',
        ),
        migrations.RemoveField(
            model_name='inventariodadosimportados',
            name='vl_residual',
        ),
    ]
