# Generated by Django 5.2.2 on 2026-06-12 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0040_bipagem_user_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bipagem',
            name='estado',
        ),
    ]
