# Generated by Django 5.2.2 on 2026-06-23 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0042_bipagem_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bipagem',
            name='estado',
            field=models.CharField(blank=True, choices=[('GOOD', 'GOOD'), ('BAD', 'BAD'), ('TRIAGEM', 'TRIAGEM'), ('OBSOLETO', 'OBSOLETO'), ('KIT GOOD', 'KIT GOOD')], max_length=100, null=True),
        ),
    ]
