# Generated by Django 5.2.2 on 2026-06-30 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0047_cronogramainventariolocal'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='bipagem',
            name='bipagem_nrserie_idx',
        ),
        migrations.RemoveIndex(
            model_name='bipagem',
            name='bipagem_lote_serial_idx',
        ),
        migrations.AlterField(
            model_name='bipagem',
            name='estado',
            field=models.CharField(blank=True, choices=[('GOOD', 'GOOD'), ('BAD', 'BAD'), ('TRIAGEM', 'TRIAGEM'), ('OBSOLETO', 'OBSOLETO'), ('SUCATA', 'SUCATA'), ('REVERSA', 'REVERSA'), ('KIT GOOD', 'KIT GOOD')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cronogramainventariolocal',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
