# Generated by Django 5.2.2 on 2026-07-01 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0049_provisionar_grupos_pa_cronograma'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cronogramainventariolocal',
            name='horario_inicio',
            field=models.TimeField(help_text='Horário oficial do inventário. O acesso libera 20 min antes (configurável).', verbose_name='Horário início'),
        ),
    ]
