# Generated by Django 5.2.2 on 2026-07-01 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0050_liberacao_pa_antecedencia_help'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cronogramainventariolocal',
            name='horario_inicio',
            field=models.TimeField(verbose_name='Horário início'),
        ),
    ]
